version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: balance_db
    environment:
      POSTGRES_USER: balance_user
      POSTGRES_PASSWORD: balance_password
      POSTGRES_DB: balance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U balance_user -d balance_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

  migrations:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    container_name: balance_migrations
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=balance_user
      - DB_PASSWORD=balance_password
      - DB_NAME=balance_db
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  app1:
    build: .
    command: npm start
    container_name: balance_app_1
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=balance_user
      - DB_PASSWORD=balance_password
      - DB_NAME=balance_db
    depends_on:
      - migrations
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  app2:
    build: .
    command: npm start
    container_name: balance_app_2
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=balance_user
      - DB_PASSWORD=balance_password
      - DB_NAME=balance_db
    depends_on:
      - migrations
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  app3:
    build: .
    command: npm start
    container_name: balance_app_3
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=balance_user
      - DB_PASSWORD=balance_password
      - DB_NAME=balance_db
    depends_on:
      - migrations
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  app4:
    build: .
    command: npm start
    container_name: balance_app_4
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - PORT=3004
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=balance_user
      - DB_PASSWORD=balance_password
      - DB_NAME=balance_db
    depends_on:
      - migrations
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  app5:
    build: .
    command: npm start
    container_name: balance_app_5
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - PORT=3005
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=balance_user
      - DB_PASSWORD=balance_password
      - DB_NAME=balance_db
    depends_on:
      - migrations
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres_data: